#### general settings
name: EDSR_fetalheadArea
model: edsr
distortion: sr
scale: 4
gpu_ids: 1

#### datasets
datasets:
  color: RGB
  test:
    name: fetal_us
    mode: LRHR
    data_folder: /home/uday/DL/SR/Data/fetal_head_data_area/test/
    Partial_train: False
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 1
    GT_size: 128
    use_flip: true
    use_rot: true
    Normalize:
      mean: 0.5
      std:  0.5

    

#### network structures
network:
  n_resblocks: 32
  n_feats: 256
  scale: 4
  rgb_range: 1
  n_colors: 3
  res_scale: 0.1

#### path
path:
  best_model: ../results/train_EDSR_fetalheadArea/EDSR_fetalheadArea_best_model.pt
  save_path: ../results/




