#### general settings
name: EDSR_liver_area
model: edsr
distortion: sr
scale: 4
gpu_ids: 2
#### datasets
datasets:
  color: RGB
  train:
    name: liver_us_area
    mode: LRHR
    #data_folder: /home/uday/DL/SR/Data/fetal_head_data_area
    data_folder: /home/uday/DL/SR/Data/liver_US/liver_us_data_area/Data_ori/
    Partial_train: False
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 1
    GT_size: 128
    use_flip: true
    use_rot: true
    Normalize:
      mean: 0.5
      std:  0.5

    

#### network structures
network:
  n_resblocks: 32
  n_feats: 256
  scale: 4
  rgb_range: 255
  n_colors: 3
  res_scale: 0.1

#### path
path:
  pretrain_model: /home/uday/DL/SR/Model/Pretrained/
  # Gives an error if '/' is not placed. Correct it. 
  save_path: ../results/

#### training settings: learning rate scheme, loss
training_params:
  num_epochs: 30
  lr_head: !!float 1e-5
  lr_body1: !!float 1e-5
  lr_body2: !!float 1e-4
  lr_tail: !!float 1e-3



